config/routes.rb
  Rails.application.routes.draw do
    root to: 'products#index'
    resources :products do
      resources :reviews
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  before_save(:titleize_product)

  scope :USA, -> { where("country_of_origin like ?", "%United States%" ) }

  scope :three_most_recent, -> {order(created_at: :desc).limit(3)}

  has_many :reviews

  validates :name, :cost, :country_of_origin, presence: true

private
  def titleize_product
    self.name = self.name.titleize
  end

  def self.usa
  where("country_of_origin like ?", "%United States%" )
  end


  def self.three_most_recent
    order(created_at:  :desc).limit(3)
  end
  
end

app/models/review.rb
class Review < ApplicationRecord
 belongs_to :product, dependent: :destroy
 validates :author, :rating, presence: true
 validates :content_body, length: { in: 50..250 }
 scope :most_popular, -> { group(:product_id).count.sort_by(&:size) }



  def self.most_popular
   group(:product_id).count.sort_by(&:size)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @product_selection = @products.name
    @usa = Product.usa
    @top = Product.three_most_recent
    @reviews = Review.all
    if @reviews.any?
      @popular_array = Review.most_popular.first
      @popular = Product.find(@popular_array[0])
    end
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
       flash[:notice] = "Your product was successfully added!"
      redirect_to products_path
    else
       flash.now[:alert]= "ooops!"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @reviews = @product.reviews
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    @reviews = Review.all

    @products = Product.all
    @product_selection = @products.name
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
    render :index
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
      @product = Product.find(params[:product_id])
        @review = @product.reviews.new(review_params)
    if @review.save
       flash.now[:notice] = "Thank you for your input!"
      redirect_to product_review_path(@product,@review)
    else
      flash.now[:alert]= "ooops!"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private

  def review_params
    params.require(:review).permit(:author, :content_body, :rating, :product_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_company_info.erb
<div class="contact_info">
<p>Contact us: ✆<a href="tel:1-000-000-000">1-369-666-1234</a> ❀ <a id = 'email', href="mailto:webmaster@example.com">fake.contact.support.none@fakemail.com</a><span id = 'logo'>❀</span></p>
</div>

app/views/layouts/_company_logo.erb
<div class="logo">
  <h1>❀Inewsit❀</h1>
  <p>All the shenanigans you could ever desire</p>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.erb
<%= render "layouts/errors", :object => @product %>
<%= form_for @product do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :cost %>
<%= f.number_field(:cost, step: 0.01) %>
<%= f.label :country_of_origin %>
<%= f.text_field :country_of_origin %>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buy/Review</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<%= render "layouts/company_logo" %>
 <h1>Edit</h1>
 <p> Name: <%= @product.name %></p>
 <p> Cost: <%= @product.cost %></p>
 <p> Made in: <%= @product.country_of_origin %></p>

<%= render "layouts/product_form", :object => @product %>

<% if @reviews.any? %>
  <h4>Here are the current reviews for this product</h4>
  <div class="add_review">
    <%= form_for @reviews do |f| %>
    <%= f.label :rating %>
    <%= f.integer :rating %>
    <%= f.label :content_body %>
    <%= f.text_field :content_body%>
    <%= f.collection_select(:product_id, @reviews, :id, :rating, :content_body)%>
    <%= f.submit  %>
    <% end %>
  </div>
<% end %>
<%= render "layouts/company_info" %>

app/views/products/index.html.erb
<%= render "layouts/company_logo" %>

<div class="categorie">

  <% if @products.any? %>
    <% if @reviews.any? %>
      <div class="most_reviews">
        <h1>Check out our most popular products</h1>
        <%= link_to @popular.name, product_path(@popular) %>
      </div>
    <% else %>
    <p>Be the first to review a product!</p>
    <% end %>

    <h1>Product list</h1>
    <ul>
      <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    </ul>

    <h1>Check out our newest products</h1>
    <ul>
      <% @top.each do |x| %>
      <li><%= link_to x.name, product_path(x) %></li>
      <% end %>
      <% else %>
      <p>There are no products yet.</p>
  <% end %>
</div>

<div class="made_in_america">
  <h1> Made in America 🇺🇸</h1>
  <% if @usa.any? %>
    <ul>
      <% @usa.each do |x| %>
      <li><%= link_to x.name, product_path(x) %></li>
      <% end %>
    </ul>
  <% else %>
    <p>There are no products made in the US.</p>
  <% end %>

  <div class="add_product">
    <p><%= link_to "New Product", new_product_path %></p>
  </div>
</div>

<%= render "layouts/company_info" %>

app/views/products/new.html.erb
<%= render "layouts/company_logo" %>

<h1>Publish a New Product </h1>

<%= render "layouts/product_form", :object => @product %>


<%= render "layouts/company_info" %>

app/views/products/show.html.erb
<%= render "layouts/company_logo" %>

<div class="product_info">
  <h3><%= @product.name %> $<%= @product.cost %></h3>

  <div class="container">
    <div class="row">
      <div class="col-sm">
        <%= link_to "Edit", edit_product_path(@product) %>
      </div>
      <div class="col-sm">
        <%= link_to "Delete", product_path(@product),
        :data => {:confirm => "You sure?",
        :method => "delete"} %>
      </div>
    </div>
  </div>
<%= image_tag href = 'https://robohash.org/nequeautqui.png?size=300x300&set=set1' %>
    <div class="description">
      <p>Glossier pork belly pabst ramps actually photo booth typewriter disrupt asymmetrical artisan brooklyn poutine. Meditation readymade heirloom keytar, austin unicorn coloring book tousled. Freegan gentrify narwhal gochujang hashtag brunch tilde glossier affogato mustache 90's VHS. Enamel pin keytar bespoke, jean shorts taxidermy man braid 3 wolf moon pinterest freegan ugh messenger bag hoodie cray.</p>

      <p>Oh. You need a little dummy text for your mockup? How quaint.</p>

      <p>I bet you’re still using Bootstrap too…</p>
    </div>

    <div class="reviews">
      <% if @product.reviews.any? %>
      <ul class = "list-group">
        <% @product.reviews.each do |x| %>
        <li class =
        "list-group-item"><p><%=  x.author %></p><p><%=  x.content_body %></p></li>
        <li class =
        "list-group-item" id = "empty_row"></li>
        <% end %>
      </ul>
      <% else %>
      <p>Be the first to review this product!</p>
      <% end %>
    </div>
    <p><%= link_to "Add a Review", new_product_review_path(@product, @review) %></p>
</div>



<p id ="return_to_products"><%= link_to "Return to products", products_path %></p>


<%= render "layouts/company_info" %>

app/views/reviews/edit.html.erb
<%= render "layouts/errors", :object => @review %>
<h1><%= @product.name %></h1>

<h3>Edit your review below</h3>
<%= form_for [@product, @review] do |f| %>
<%= f.label :author %>
<%= f.text_field :author%>
<%= f.label :rating %>
<%= f.number_field :rating, in: 1..5 %>
<%= f.label :content_body %>
<%= f.text_area :content_body%>
<%= f.submit  %>
<% end %>


<%= render "layouts/company_info" %>

app/views/reviews/index.html.erb
<%= render "layouts/company_logo" %>

<%= render "layouts/company_info" %>

app/views/reviews/new.html.erb
<%= render "layouts/errors", :object => @review %>
<h1><%= @product.name %></h1>
<h3>Write your review below</h3>
<%= form_for [@product, @review] do |f| %>
<%= f.label :author %>
<%= f.text_field :author%>
<%= f.label :rating %>
<%= f.number_field :rating, in: 1..5 %>
<%= f.label :content_body %>
<%= f.text_area :content_body%>

<%= f.submit  %>
<% end %>


<%= render "layouts/company_info" %>

app/views/reviews/show.html.erb
<%= render "layouts/company_logo" %>
<h1><%= @product.name %></h1>
<div class="product_image">
  <%= image_tag href = 'https://picsum.photos/seed/picsum/200' %>
</div>
<div class="reviews">
  <% if @product.reviews %>
    <% @product.reviews.each do |review| %>
      <ul>
        <li>Written by: <%= review.author %></li>
        <ul>
          <li> Rating: <%= review.rating %></li>
          <p><%= review.content_body %></p>
        </ul>
      </ul>
    <% end %>
  <% end%>
</div>

<%= render "layouts/company_info" %>